...

diff --git a/.github/workflows/prod.yml b/.github/workflows/prod.yml
--- a/.github/workflows/prod.yml
+++ b/.github/workflows/prod.yml
@@ -25,26 +25,37 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Log in to DockerHub
-        run: echo ${{DOCKERHUB_PASSWORD}} | docker login -u ${{DOCKERHUB_USERNAME}} --password-stdin
+        run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
 
       - name: Build and push Docker image
         run: |
-          echo "DOCKERHUB_USERNAME is: ${{DOCKERHUB_USERNAME}}"
-          echo "IMAGE_NAME is: ${{IMAGE_NAME}}"
-          echo "Building Docker image: ${{IMAGE_NAME}}:${{TAG}}"
-          docker build -t ${{IMAGE_NAME}}:${{TAG}} .
-          docker push ${{IMAGE_NAME}}:${{TAG}}
+          echo "DOCKERHUB_USERNAME is: $DOCKERHUB_USERNAME"
+          echo "IMAGE_NAME is: $IMAGE_NAME"
+          echo "TAG is: $TAG"
+          echo "ENV_FILE_NAME is: $ENV_FILE_NAME"
+          echo "Building Docker image: $IMAGE_NAME:$TAG"
+          docker build -t "$IMAGE_NAME:$TAG" .
+          docker push "$IMAGE_NAME:$TAG"
 
       - name: Deploy to VPS via SSH
-        uses: appleboy/ssh-action@v0.1.3
+        uses: appleboy/ssh-action@v1.0.3
         with:
-          host: ${{VPS_HOST}}
-          username: ${{VPS_USER}}
-          key: ${{SSH_KEY}}
-          envs: IMAGE_NAME,TAG,ENV_FILE_NAME,CONTAINER_NAME
+          host: ${{ env.VPS_HOST }}
+          username: ${{ env.VPS_USER }}
+          key: ${{ env.SSH_KEY }}
+          envs: IMAGE_NAME,TAG,ENV_FILE_NAME,CONTAINER_NAME,DOCKERHUB_USERNAME,DOCKERHUB_PASSWORD
           script: |
-            docker login -u ${{DOCKERHUB_USERNAME}} -p ${{DOCKERHUB_PASSWORD}}
-            docker pull ${{IMAGE_NAME}}:${{TAG}}
-            docker stop ${{CONTAINER_NAME}} || true
-            docker rm ${{CONTAINER_NAME}} || true
-            docker run -d --name ${{CONTAINER_NAME}} -p 8000:8000 --env-file ${{ENV_FILE_NAME}} ${{IMAGE_NAME}}:${{TAG}}
+            echo "Debug: IMAGE_NAME is: $IMAGE_NAME"
+            echo "Debug: TAG is: $TAG"
+            echo "Debug: ENV_FILE_NAME is: $ENV_FILE_NAME"
+            echo "Debug: CONTAINER_NAME is: $CONTAINER_NAME"
+            echo "Debug: DOCKERHUB_USERNAME is: $DOCKERHUB_USERNAME"
+            if [ ! -f "$ENV_FILE_NAME" ]; then
+              echo "Error: Environment file $ENV_FILE_NAME does not exist. Dilshod "
+              exit 1
+            fi
+            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
+            docker pull "$IMAGE_NAME:$TAG"
+            docker stop "$CONTAINER_NAME" || true
+            docker rm "$CONTAINER_NAME" || true
+            docker run -d --name "$CONTAINER_NAME" -p 8000:8000 --env-file "$ENV_FILE_NAME" "$IMAGE_NAME:$TAG"
